// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using My.Talli.Domain.Data.EntityFramework;

#nullable disable

namespace My.Talli.Domain.Data.EntityFramework.Migrations
{
    [DbContext(typeof(TalliDbContext))]
    [Migration("20260419090634_MoveTokensToShopConnection")]
    partial class MoveTokensToShopConnection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.2.25163.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("My.Talli.Domain.Entities.AuthenticatedUser", b =>
                {
                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredProvider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("vAuthenticatedUser", "auth");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.Billing", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("money")
                        .HasColumnOrder(3);

                    b.Property<long>("CreateByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(8);

                    b.Property<DateTime>("CreatedOnDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9);

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnOrder(4);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(6);

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit")
                        .HasColumnOrder(7);

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnOrder(5);

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(10);

                    b.Property<DateTime?>("UpdatedOnDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(11);

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.HasKey("Id")
                        .HasName("PK_Billing");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_Billing_OrderId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Billing_UserId");

                    b.ToTable("Billing", "commerce");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.BillingStripe", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("BillingId")
                        .HasColumnOrder(0);

                    b.Property<string>("CardBrand")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnOrder(1);

                    b.Property<string>("CardLastFour")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnOrder(2);

                    b.Property<long>("CreateByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(7);

                    b.Property<DateTime>("CreatedOnDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(8);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(5);

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit")
                        .HasColumnOrder(6);

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(3);

                    b.Property<string>("StripePaymentIntentId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnOrder(4);

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(9);

                    b.Property<DateTime?>("UpdatedOnDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(10);

                    b.HasKey("Id")
                        .HasName("PK_BillingStripe");

                    b.ToTable("BillingStripe", "commerce");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.Expense", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnOrder(3);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(4);

                    b.Property<long>("CreateByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(12);

                    b.Property<DateTime>("CreatedOnDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(13);

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnOrder(5);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnOrder(6);

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(7);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(10);

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit")
                        .HasColumnOrder(11);

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(8);

                    b.Property<string>("PlatformTransactionId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnOrder(9);

                    b.Property<long?>("ShopConnectionId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(14);

                    b.Property<DateTime?>("UpdatedOnDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(15);

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.HasKey("Id")
                        .HasName("PK_Expense");

                    b.HasIndex("ShopConnectionId")
                        .HasDatabaseName("IX_Expense_ShopConnectionId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Expense_UserId");

                    b.HasIndex("Platform", "ExpenseDate")
                        .HasDatabaseName("IX_Expense_Platform_ExpenseDate");

                    b.ToTable("Expense", "app");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.Goal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CreateByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(10);

                    b.Property<DateTime>("CreatedOnDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(11);

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(3);

                    b.Property<long>("GoalTypeId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(8);

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit")
                        .HasColumnOrder(9);

                    b.Property<string>("Platform")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(4);

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(5);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnOrder(6);

                    b.Property<decimal>("TargetAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnOrder(7);

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(12);

                    b.Property<DateTime?>("UpdatedOnDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(13);

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.HasKey("Id")
                        .HasName("PK_Goal");

                    b.HasIndex("GoalTypeId")
                        .HasDatabaseName("IX_Goal_GoalTypeId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Goal_UserId");

                    b.ToTable("Goal", "app");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.GoalType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CreateByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(4);

                    b.Property<DateTime>("CreatedOnDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(5);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(2);

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit")
                        .HasColumnOrder(3);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(1);

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("UpdatedOnDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(7);

                    b.HasKey("Id")
                        .HasName("PK_GoalType");

                    b.ToTable("GoalType", "app");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CreateByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(6);

                    b.Property<DateTime>("CreatedOnDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(7);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(4);

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("OrderDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(2);

                    b.Property<decimal>("TaxCharged")
                        .HasColumnType("money")
                        .HasColumnOrder(3);

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(8);

                    b.Property<DateTime?>("UpdatedOnDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9);

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.HasKey("Id")
                        .HasName("PK_Order");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Order_UserId");

                    b.ToTable("Order", "commerce");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.OrderItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CreateByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(7);

                    b.Property<DateTime>("CreatedOnDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(8);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(5);

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit")
                        .HasColumnOrder(6);

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.Property<decimal>("ProductPriceCharged")
                        .HasColumnType("money")
                        .HasColumnOrder(3);

                    b.Property<int>("ProductQuantity")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(9);

                    b.Property<DateTime?>("UpdatedOnDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(10);

                    b.HasKey("Id")
                        .HasName("PK_OrderItem");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_OrderItem_OrderId");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_OrderItem_ProductId");

                    b.ToTable("OrderItem", "commerce");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.Payout", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnOrder(3);

                    b.Property<long>("CreateByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(12);

                    b.Property<DateTime>("CreatedOnDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(13);

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnOrder(4);

                    b.Property<DateTime?>("ExpectedArrivalDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(5);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(10);

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit")
                        .HasColumnOrder(11);

                    b.Property<DateTime>("PayoutDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(6);

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(7);

                    b.Property<string>("PlatformPayoutId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnOrder(8);

                    b.Property<long?>("ShopConnectionId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnOrder(9);

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(14);

                    b.Property<DateTime?>("UpdatedOnDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(15);

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.HasKey("Id")
                        .HasName("PK_Payout");

                    b.HasIndex("PlatformPayoutId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Payout_PlatformPayoutId");

                    b.HasIndex("ShopConnectionId")
                        .HasDatabaseName("IX_Payout_ShopConnectionId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Payout_UserId");

                    b.HasIndex("Platform", "PayoutDate")
                        .HasDatabaseName("IX_Payout_Platform_PayoutDate");

                    b.ToTable("Payout", "app");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.PlatformConnection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ConnectionStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(2);

                    b.Property<long>("CreateByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(6);

                    b.Property<DateTime>("CreatedOnDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(7);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(4);

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit")
                        .HasColumnOrder(5);

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(3);

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(8);

                    b.Property<DateTime?>("UpdatedOnDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9);

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.HasKey("Id")
                        .HasName("PK_PlatformConnection");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_PlatformConnection_UserId");

                    b.HasIndex("UserId", "Platform")
                        .IsUnique()
                        .HasDatabaseName("UQ_PlatformConnection_UserId_Platform");

                    b.ToTable("PlatformConnection", "app");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CreateByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(7);

                    b.Property<DateTime>("CreatedOnDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(8);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(5);

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit")
                        .HasColumnOrder(6);

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(3);

                    b.Property<long>("ProductTypeId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(9);

                    b.Property<DateTime?>("UpdatedOnDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(10);

                    b.Property<long>("VendorId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.Property<decimal>("VendorPrice")
                        .HasColumnType("money")
                        .HasColumnOrder(4);

                    b.HasKey("Id")
                        .HasName("PK_Product");

                    b.HasIndex("ProductTypeId")
                        .HasDatabaseName("IX_Product_ProductTypeId");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("IX_Product_VendorId");

                    b.ToTable("Product", "commerce");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.ProductType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CreateByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(4);

                    b.Property<DateTime>("CreatedOnDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(5);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(2);

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit")
                        .HasColumnOrder(3);

                    b.Property<string>("ProductTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(1);

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("UpdatedOnDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(7);

                    b.HasKey("Id")
                        .HasName("PK_ProductType");

                    b.ToTable("ProductType", "commerce");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.ProductVendor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CreateByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(4);

                    b.Property<DateTime>("CreatedOnDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(5);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(2);

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit")
                        .HasColumnOrder(3);

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("UpdatedOnDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(7);

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(1);

                    b.HasKey("Id")
                        .HasName("PK_ProductVendor");

                    b.ToTable("ProductVendor", "commerce");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.Revenue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CreateByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(15);

                    b.Property<DateTime>("CreatedOnDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(16);

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnOrder(3);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnOrder(4);

                    b.Property<decimal>("FeeAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnOrder(5);

                    b.Property<decimal>("GrossAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnOrder(6);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(13);

                    b.Property<bool>("IsDisputed")
                        .HasColumnType("bit")
                        .HasColumnOrder(7);

                    b.Property<bool>("IsRefunded")
                        .HasColumnType("bit")
                        .HasColumnOrder(8);

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit")
                        .HasColumnOrder(14);

                    b.Property<decimal>("NetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnOrder(9);

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(10);

                    b.Property<string>("PlatformTransactionId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnOrder(11);

                    b.Property<long?>("ShopConnectionId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(12);

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(17);

                    b.Property<DateTime?>("UpdatedOnDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(18);

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.HasKey("Id")
                        .HasName("PK_Revenue");

                    b.HasIndex("ShopConnectionId")
                        .HasDatabaseName("IX_Revenue_ShopConnectionId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Revenue_UserId");

                    b.HasIndex("Platform", "TransactionDate")
                        .HasDatabaseName("IX_Revenue_Platform_TransactionDate");

                    b.ToTable("Revenue", "app");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.RevenueEtsy", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("RevenueId")
                        .HasColumnOrder(0);

                    b.Property<decimal?>("AdjustedFees")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnOrder(1);

                    b.Property<decimal?>("AdjustedGross")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnOrder(2);

                    b.Property<decimal?>("AdjustedNet")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnOrder(3);

                    b.Property<long>("CreateByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(9);

                    b.Property<DateTime>("CreatedOnDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(10);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(7);

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit")
                        .HasColumnOrder(8);

                    b.Property<long>("ListingId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(4);

                    b.Property<long>("ReceiptId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(5);

                    b.Property<string>("ShopCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnOrder(6);

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(11);

                    b.Property<DateTime?>("UpdatedOnDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(12);

                    b.HasKey("Id")
                        .HasName("PK_RevenueEtsy");

                    b.ToTable("RevenueEtsy", "app");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.RevenueGumroad", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("RevenueId")
                        .HasColumnOrder(0);

                    b.Property<long>("CreateByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(6);

                    b.Property<DateTime>("CreatedOnDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(7);

                    b.Property<decimal?>("DiscoverFee")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(4);

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit")
                        .HasColumnOrder(5);

                    b.Property<string>("LicenseKey")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnOrder(2);

                    b.Property<string>("SaleId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnOrder(3);

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(8);

                    b.Property<DateTime?>("UpdatedOnDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9);

                    b.HasKey("Id")
                        .HasName("PK_RevenueGumroad");

                    b.ToTable("RevenueGumroad", "app");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.RevenueManual", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("RevenueId")
                        .HasColumnOrder(0);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(1);

                    b.Property<long>("CreateByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(6);

                    b.Property<DateTime>("CreatedOnDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(7);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(4);

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit")
                        .HasColumnOrder(5);

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnOrder(2);

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnOrder(3);

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(8);

                    b.Property<DateTime?>("UpdatedOnDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9);

                    b.HasKey("Id")
                        .HasName("PK_RevenueManual");

                    b.ToTable("RevenueManual", "app");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.RevenueStripe", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("RevenueId")
                        .HasColumnOrder(0);

                    b.Property<string>("BalanceTransactionId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnOrder(1);

                    b.Property<long>("CreateByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(7);

                    b.Property<DateTime>("CreatedOnDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(8);

                    b.Property<decimal?>("ExchangeRate")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnOrder(2);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(5);

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit")
                        .HasColumnOrder(6);

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(3);

                    b.Property<int?>("RiskScore")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(9);

                    b.Property<DateTime?>("UpdatedOnDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(10);

                    b.HasKey("Id")
                        .HasName("PK_RevenueStripe");

                    b.ToTable("RevenueStripe", "app");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.ShopConnection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(3);

                    b.Property<int>("ConsecutiveFailures")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnOrder(4);

                    b.Property<long>("CreateByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(18);

                    b.Property<DateTime>("CreatedOnDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(19);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(5);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(16);

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(6);

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit")
                        .HasColumnOrder(17);

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnOrder(7);

                    b.Property<DateTime?>("LastSyncDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(8);

                    b.Property<DateTime>("NextSyncDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9);

                    b.Property<string>("PlatformAccountId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnOrder(10);

                    b.Property<long>("PlatformConnectionId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<string>("PlatformShopId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnOrder(11);

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(12);

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnOrder(13);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnOrder(14);

                    b.Property<DateTime?>("TokenExpiryDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(15);

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(20);

                    b.Property<DateTime?>("UpdatedOnDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(21);

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.HasKey("Id")
                        .HasName("PK_ShopConnection");

                    b.HasIndex("PlatformConnectionId")
                        .HasDatabaseName("IX_ShopConnection_PlatformConnectionId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_ShopConnection_UserId");

                    b.HasIndex("NextSyncDateTime", "Status")
                        .HasDatabaseName("IX_ShopConnection_NextSyncDateTime_Status");

                    b.HasIndex("PlatformConnectionId", "PlatformShopId")
                        .IsUnique()
                        .HasDatabaseName("UQ_ShopConnection_PlatformConnectionId_PlatformShopId");

                    b.ToTable("ShopConnection", "app");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.ShopConnectionEtsy", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("ShopConnectionId")
                        .HasColumnOrder(0);

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .HasColumnOrder(1)
                        .IsFixedLength();

                    b.Property<long>("CreateByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(7);

                    b.Property<DateTime>("CreatedOnDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(8);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(5);

                    b.Property<bool>("IsVacationMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnOrder(2);

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit")
                        .HasColumnOrder(6);

                    b.Property<string>("ShopCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .HasColumnOrder(3)
                        .IsFixedLength();

                    b.Property<string>("ShopUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnOrder(4);

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(9);

                    b.Property<DateTime?>("UpdatedOnDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(10);

                    b.HasKey("Id")
                        .HasName("PK_ShopConnectionEtsy");

                    b.ToTable("ShopConnectionEtsy", "app");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.Subscription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CancelledDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(4);

                    b.Property<long>("CreateByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(11);

                    b.Property<DateTime>("CreatedOnDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(12);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(5);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(9);

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit")
                        .HasColumnOrder(10);

                    b.Property<long>("OrderItemId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("RenewalDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(6);

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(7);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnOrder(8);

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(13);

                    b.Property<DateTime?>("UpdatedOnDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(14);

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(3);

                    b.HasKey("Id")
                        .HasName("PK_Subscription");

                    b.HasIndex("OrderItemId")
                        .HasDatabaseName("IX_Subscription_OrderItemId");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_Subscription_ProductId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Subscription_UserId");

                    b.ToTable("Subscription", "commerce");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.SubscriptionStripe", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("SubscriptionId")
                        .HasColumnOrder(0);

                    b.Property<long>("CreateByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(6);

                    b.Property<DateTime>("CreatedOnDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(7);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(4);

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit")
                        .HasColumnOrder(5);

                    b.Property<string>("StripeCustomerId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnOrder(1);

                    b.Property<string>("StripePriceId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnOrder(2);

                    b.Property<string>("StripeSubscriptionId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnOrder(3);

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(8);

                    b.Property<DateTime?>("UpdatedOnDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9);

                    b.HasKey("Id")
                        .HasName("PK_SubscriptionStripe");

                    b.ToTable("SubscriptionStripe", "commerce");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.Suggestion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AdminNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnOrder(2);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(3);

                    b.Property<long>("CreateByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(9);

                    b.Property<DateTime>("CreatedOnDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(10);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnOrder(4);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(7);

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit")
                        .HasColumnOrder(8);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnOrder(5);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnOrder(6);

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(11);

                    b.Property<DateTime?>("UpdatedOnDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(12);

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.HasKey("Id")
                        .HasName("PK_Suggestion");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Suggestion_UserId");

                    b.ToTable("Suggestion", "app");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.SuggestionVote", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CreateByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("CreatedOnDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(6);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(3);

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit")
                        .HasColumnOrder(4);

                    b.Property<long>("SuggestionId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(7);

                    b.Property<DateTime?>("UpdatedOnDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(8);

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.HasKey("Id")
                        .HasName("PK_SuggestionVote");

                    b.HasIndex("SuggestionId")
                        .HasDatabaseName("IX_SuggestionVote_SuggestionId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_SuggestionVote_UserId");

                    b.HasIndex("SuggestionId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("UQ_SuggestionVote_SuggestionId_UserId");

                    b.ToTable("SuggestionVote", "app");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CreateByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(10);

                    b.Property<DateTime>("CreatedOnDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(11);

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(2);

                    b.Property<string>("InitialProvider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnOrder(3);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(8);

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit")
                        .HasColumnOrder(9);

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(4);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(5);

                    b.Property<string>("PreferredProvider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnOrder(6);

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(12);

                    b.Property<DateTime?>("UpdatedOnDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(13);

                    b.Property<string>("UserPreferences")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(7);

                    b.HasKey("Id")
                        .HasName("PK_User");

                    b.ToTable("User", "auth");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.UserAuthenticationApple", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("UserId")
                        .HasColumnOrder(0);

                    b.Property<string>("AppleId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnOrder(1);

                    b.Property<long>("CreateByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(9);

                    b.Property<DateTime>("CreatedOnDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(10);

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(2);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnOrder(3);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(4);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(7);

                    b.Property<bool>("IsPrivateRelay")
                        .HasColumnType("bit")
                        .HasColumnOrder(5);

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit")
                        .HasColumnOrder(8);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(6);

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(11);

                    b.Property<DateTime?>("UpdatedOnDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(12);

                    b.HasKey("Id")
                        .HasName("PK_UserAuthApple");

                    b.HasIndex("AppleId")
                        .IsUnique()
                        .HasDatabaseName("UQ_UserAuthApple_AppleId");

                    b.ToTable("UserAuthenticationApple", "auth");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.UserAuthenticationGoogle", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("UserId")
                        .HasColumnOrder(0);

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnOrder(1);

                    b.Property<long>("CreateByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(11);

                    b.Property<DateTime>("CreatedOnDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(12);

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(2);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnOrder(3);

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("bit")
                        .HasColumnOrder(4);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(5);

                    b.Property<string>("GoogleId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnOrder(6);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(9);

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit")
                        .HasColumnOrder(10);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(7);

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnOrder(8);

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(13);

                    b.Property<DateTime?>("UpdatedOnDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(14);

                    b.HasKey("Id")
                        .HasName("PK_UserAuthGoogle");

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasDatabaseName("UQ_UserAuthGoogle_GoogleId");

                    b.ToTable("UserAuthenticationGoogle", "auth");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.UserAuthenticationMicrosoft", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("UserId")
                        .HasColumnOrder(0);

                    b.Property<long>("CreateByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(8);

                    b.Property<DateTime>("CreatedOnDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9);

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnOrder(2);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(3);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(6);

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit")
                        .HasColumnOrder(7);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(4);

                    b.Property<string>("MicrosoftId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnOrder(5);

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(10);

                    b.Property<DateTime?>("UpdatedOnDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(11);

                    b.HasKey("Id")
                        .HasName("PK_UserAuthMicrosoft");

                    b.HasIndex("MicrosoftId")
                        .IsUnique()
                        .HasDatabaseName("UQ_UserAuthMicrosoft_MicrosoftId");

                    b.ToTable("UserAuthenticationMicrosoft", "auth");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.UserRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CreateByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("CreatedOnDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(6);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(3);

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit")
                        .HasColumnOrder(4);

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(2);

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(7);

                    b.Property<DateTime?>("UpdatedOnDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(8);

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.HasKey("Id")
                        .HasName("PK_UserRole");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserRole_UserId");

                    b.HasIndex("UserId", "Role")
                        .IsUnique()
                        .HasDatabaseName("UQ_UserRole_UserId_Role");

                    b.ToTable("UserRole", "auth");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.Billing", b =>
                {
                    b.HasOne("My.Talli.Domain.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Billing_Order");

                    b.HasOne("My.Talli.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Billing_User");

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.BillingStripe", b =>
                {
                    b.HasOne("My.Talli.Domain.Entities.Billing", "Billing")
                        .WithOne()
                        .HasForeignKey("My.Talli.Domain.Entities.BillingStripe", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BillingStripe_Billing");

                    b.Navigation("Billing");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.Expense", b =>
                {
                    b.HasOne("My.Talli.Domain.Entities.ShopConnection", "ShopConnection")
                        .WithMany()
                        .HasForeignKey("ShopConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Expense_ShopConnection");

                    b.HasOne("My.Talli.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Expense_User");

                    b.Navigation("ShopConnection");

                    b.Navigation("User");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.Goal", b =>
                {
                    b.HasOne("My.Talli.Domain.Entities.GoalType", "GoalType")
                        .WithMany()
                        .HasForeignKey("GoalTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Goal_GoalType");

                    b.HasOne("My.Talli.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Goal_User");

                    b.Navigation("GoalType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.Order", b =>
                {
                    b.HasOne("My.Talli.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Order_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("My.Talli.Domain.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OrderItem_Order");

                    b.HasOne("My.Talli.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OrderItem_Product");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.Payout", b =>
                {
                    b.HasOne("My.Talli.Domain.Entities.ShopConnection", "ShopConnection")
                        .WithMany()
                        .HasForeignKey("ShopConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Payout_ShopConnection");

                    b.HasOne("My.Talli.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Payout_User");

                    b.Navigation("ShopConnection");

                    b.Navigation("User");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.PlatformConnection", b =>
                {
                    b.HasOne("My.Talli.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PlatformConnection_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.Product", b =>
                {
                    b.HasOne("My.Talli.Domain.Entities.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Product_ProductType");

                    b.HasOne("My.Talli.Domain.Entities.ProductVendor", "ProductVendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Product_ProductVendor");

                    b.Navigation("ProductType");

                    b.Navigation("ProductVendor");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.Revenue", b =>
                {
                    b.HasOne("My.Talli.Domain.Entities.ShopConnection", "ShopConnection")
                        .WithMany()
                        .HasForeignKey("ShopConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Revenue_ShopConnection");

                    b.HasOne("My.Talli.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Revenue_User");

                    b.Navigation("ShopConnection");

                    b.Navigation("User");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.RevenueEtsy", b =>
                {
                    b.HasOne("My.Talli.Domain.Entities.Revenue", "Revenue")
                        .WithOne()
                        .HasForeignKey("My.Talli.Domain.Entities.RevenueEtsy", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RevenueEtsy_Revenue");

                    b.Navigation("Revenue");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.RevenueGumroad", b =>
                {
                    b.HasOne("My.Talli.Domain.Entities.Revenue", "Revenue")
                        .WithOne()
                        .HasForeignKey("My.Talli.Domain.Entities.RevenueGumroad", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RevenueGumroad_Revenue");

                    b.Navigation("Revenue");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.RevenueManual", b =>
                {
                    b.HasOne("My.Talli.Domain.Entities.Revenue", "Revenue")
                        .WithOne()
                        .HasForeignKey("My.Talli.Domain.Entities.RevenueManual", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RevenueManual_Revenue");

                    b.Navigation("Revenue");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.RevenueStripe", b =>
                {
                    b.HasOne("My.Talli.Domain.Entities.Revenue", "Revenue")
                        .WithOne()
                        .HasForeignKey("My.Talli.Domain.Entities.RevenueStripe", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RevenueStripe_Revenue");

                    b.Navigation("Revenue");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.ShopConnection", b =>
                {
                    b.HasOne("My.Talli.Domain.Entities.PlatformConnection", "PlatformConnection")
                        .WithMany()
                        .HasForeignKey("PlatformConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ShopConnection_PlatformConnection");

                    b.HasOne("My.Talli.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ShopConnection_User");

                    b.Navigation("PlatformConnection");

                    b.Navigation("User");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.ShopConnectionEtsy", b =>
                {
                    b.HasOne("My.Talli.Domain.Entities.ShopConnection", "ShopConnection")
                        .WithOne()
                        .HasForeignKey("My.Talli.Domain.Entities.ShopConnectionEtsy", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ShopConnectionEtsy_ShopConnection");

                    b.Navigation("ShopConnection");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("My.Talli.Domain.Entities.OrderItem", "OrderItem")
                        .WithMany()
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Subscription_OrderItem");

                    b.HasOne("My.Talli.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Subscription_Product");

                    b.HasOne("My.Talli.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Subscription_User");

                    b.Navigation("OrderItem");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.SubscriptionStripe", b =>
                {
                    b.HasOne("My.Talli.Domain.Entities.Subscription", "Subscription")
                        .WithOne()
                        .HasForeignKey("My.Talli.Domain.Entities.SubscriptionStripe", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SubscriptionStripe_Subscription");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.Suggestion", b =>
                {
                    b.HasOne("My.Talli.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Suggestion_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.SuggestionVote", b =>
                {
                    b.HasOne("My.Talli.Domain.Entities.Suggestion", "Suggestion")
                        .WithMany()
                        .HasForeignKey("SuggestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SuggestionVote_Suggestion");

                    b.HasOne("My.Talli.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_SuggestionVote_User");

                    b.Navigation("Suggestion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.UserAuthenticationApple", b =>
                {
                    b.HasOne("My.Talli.Domain.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("My.Talli.Domain.Entities.UserAuthenticationApple", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserAuthApple_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.UserAuthenticationGoogle", b =>
                {
                    b.HasOne("My.Talli.Domain.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("My.Talli.Domain.Entities.UserAuthenticationGoogle", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserAuthGoogle_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.UserAuthenticationMicrosoft", b =>
                {
                    b.HasOne("My.Talli.Domain.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("My.Talli.Domain.Entities.UserAuthenticationMicrosoft", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserAuthMicrosoft_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("My.Talli.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserRole_User");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
