// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using My.Talli.Domain.Data.EntityFramework;

#nullable disable

namespace My.Talli.Domain.Data.EntityFramework.Migrations
{
    [DbContext(typeof(TalliDbContext))]
    [Migration("20260315112521_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.2.25163.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("My.Talli.Domain.Entities.Billing", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("money")
                        .HasColumnOrder(3);

                    b.Property<long>("CreateByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(7);

                    b.Property<DateTime>("CreatedOnDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(8);

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnOrder(4);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnOrder(6);

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnOrder(5);

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(9);

                    b.Property<DateTime?>("UpdatedOnDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(10);

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.HasKey("Id")
                        .HasName("PK_Billing");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_Billing_OrderId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Billing_UserId");

                    b.ToTable("Billing", "commerce");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.BillingStripe", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    b.Property<string>("CardBrand")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnOrder(1);

                    b.Property<string>("CardLastFour")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnOrder(2);

                    b.Property<long>("CreateByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(6);

                    b.Property<DateTime>("CreatedOnDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(7);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnOrder(5);

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(3);

                    b.Property<string>("StripePaymentIntentId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnOrder(4);

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(8);

                    b.Property<DateTime?>("UpdatedOnDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9);

                    b.HasKey("Id")
                        .HasName("PK_BillingStripe");

                    b.ToTable("BillingStripe", "commerce");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CreateByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("CreatedOnDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(6);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnOrder(4);

                    b.Property<DateTime>("OrderDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(2);

                    b.Property<decimal>("TaxCharged")
                        .HasColumnType("money")
                        .HasColumnOrder(3);

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(7);

                    b.Property<DateTime?>("UpdatedOnDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(8);

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.HasKey("Id")
                        .HasName("PK_Order");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Order_UserId");

                    b.ToTable("Order", "commerce");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.OrderItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CreateByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(6);

                    b.Property<DateTime>("CreatedOnDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(7);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnOrder(5);

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.Property<decimal>("ProductPriceCharged")
                        .HasColumnType("money")
                        .HasColumnOrder(3);

                    b.Property<int>("ProductQuantity")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(8);

                    b.Property<DateTime?>("UpdatedOnDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9);

                    b.HasKey("Id")
                        .HasName("PK_OrderItem");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_OrderItem_OrderId");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_OrderItem_ProductId");

                    b.ToTable("OrderItem", "commerce");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CreateByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(6);

                    b.Property<DateTime>("CreatedOnDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(7);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnOrder(5);

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(3);

                    b.Property<long>("ProductTypeId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(8);

                    b.Property<DateTime?>("UpdatedOnDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9);

                    b.Property<long>("VendorId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.Property<decimal>("VendorPrice")
                        .HasColumnType("money")
                        .HasColumnOrder(4);

                    b.HasKey("Id")
                        .HasName("PK_Product");

                    b.HasIndex("ProductTypeId")
                        .HasDatabaseName("IX_Product_ProductTypeId");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("IX_Product_VendorId");

                    b.ToTable("Product", "commerce");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.ProductType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CreateByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("CreatedOnDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(4);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnOrder(2);

                    b.Property<string>("ProductTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(1);

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(5);

                    b.Property<DateTime?>("UpdatedOnDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(6);

                    b.HasKey("Id")
                        .HasName("PK_ProductType");

                    b.ToTable("ProductType", "commerce");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.ProductVendor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CreateByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("CreatedOnDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(4);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnOrder(2);

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(5);

                    b.Property<DateTime?>("UpdatedOnDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(6);

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(1);

                    b.HasKey("Id")
                        .HasName("PK_ProductVendor");

                    b.ToTable("ProductVendor", "commerce");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.Subscription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CancelledDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(4);

                    b.Property<long>("CreateByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(10);

                    b.Property<DateTime>("CreatedOnDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(11);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(5);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnOrder(9);

                    b.Property<long>("OrderItemId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("RenewalDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(6);

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(7);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnOrder(8);

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(12);

                    b.Property<DateTime?>("UpdatedOnDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(13);

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(3);

                    b.HasKey("Id")
                        .HasName("PK_Subscription");

                    b.HasIndex("OrderItemId")
                        .HasDatabaseName("IX_Subscription_OrderItemId");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_Subscription_ProductId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Subscription_UserId");

                    b.ToTable("Subscription", "commerce");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.SubscriptionStripe", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    b.Property<long>("CreateByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("CreatedOnDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(6);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnOrder(4);

                    b.Property<string>("StripeCustomerId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnOrder(1);

                    b.Property<string>("StripePriceId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnOrder(2);

                    b.Property<string>("StripeSubscriptionId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnOrder(3);

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(7);

                    b.Property<DateTime?>("UpdatedOnDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(8);

                    b.HasKey("Id")
                        .HasName("PK_SubscriptionStripe");

                    b.ToTable("SubscriptionStripe", "commerce");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CreateByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(9);

                    b.Property<DateTime>("CreatedOnDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(10);

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(2);

                    b.Property<string>("InitialProvider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnOrder(3);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnOrder(8);

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(4);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(5);

                    b.Property<string>("PreferredProvider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnOrder(6);

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(11);

                    b.Property<DateTime?>("UpdatedOnDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(12);

                    b.Property<string>("UserPreferences")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(7);

                    b.HasKey("Id")
                        .HasName("PK_User");

                    b.ToTable("User", "auth");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.UserAuthenticationApple", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    b.Property<string>("AppleId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnOrder(1);

                    b.Property<long>("CreateByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(8);

                    b.Property<DateTime>("CreatedOnDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9);

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(2);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnOrder(3);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(4);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnOrder(7);

                    b.Property<bool>("IsPrivateRelay")
                        .HasColumnType("bit")
                        .HasColumnOrder(5);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(6);

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(10);

                    b.Property<DateTime?>("UpdatedOnDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(11);

                    b.HasKey("Id")
                        .HasName("PK_UserAuthApple");

                    b.HasIndex("AppleId")
                        .IsUnique()
                        .HasDatabaseName("UQ_UserAuthApple_AppleId");

                    b.ToTable("UserAuthenticationApple", "auth");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.UserAuthenticationGoogle", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnOrder(1);

                    b.Property<long>("CreateByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(10);

                    b.Property<DateTime>("CreatedOnDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(11);

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(2);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnOrder(3);

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("bit")
                        .HasColumnOrder(4);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(5);

                    b.Property<string>("GoogleId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnOrder(6);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnOrder(9);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(7);

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnOrder(8);

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(12);

                    b.Property<DateTime?>("UpdatedOnDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(13);

                    b.HasKey("Id")
                        .HasName("PK_UserAuthGoogle");

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasDatabaseName("UQ_UserAuthGoogle_GoogleId");

                    b.ToTable("UserAuthenticationGoogle", "auth");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.UserAuthenticationMicrosoft", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    b.Property<long>("CreateByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(7);

                    b.Property<DateTime>("CreatedOnDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(8);

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnOrder(2);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(3);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnOrder(6);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(4);

                    b.Property<string>("MicrosoftId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnOrder(5);

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(9);

                    b.Property<DateTime?>("UpdatedOnDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(10);

                    b.HasKey("Id")
                        .HasName("PK_UserAuthMicrosoft");

                    b.HasIndex("MicrosoftId")
                        .IsUnique()
                        .HasDatabaseName("UQ_UserAuthMicrosoft_MicrosoftId");

                    b.ToTable("UserAuthenticationMicrosoft", "auth");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.UserRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CreateByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(4);

                    b.Property<DateTime>("CreatedOnDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(5);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnOrder(3);

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(2);

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("UpdatedOnDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(7);

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.HasKey("Id")
                        .HasName("PK_UserRole");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserRole_UserId");

                    b.HasIndex("UserId", "Role")
                        .IsUnique()
                        .HasDatabaseName("UQ_UserRole_UserId_Role");

                    b.ToTable("UserRole", "auth");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.Billing", b =>
                {
                    b.HasOne("My.Talli.Domain.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Billing_Order");

                    b.HasOne("My.Talli.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Billing_User");

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.BillingStripe", b =>
                {
                    b.HasOne("My.Talli.Domain.Entities.Billing", "Billing")
                        .WithOne()
                        .HasForeignKey("My.Talli.Domain.Entities.BillingStripe", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BillingStripe_Billing");

                    b.Navigation("Billing");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.Order", b =>
                {
                    b.HasOne("My.Talli.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Order_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("My.Talli.Domain.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OrderItem_Order");

                    b.HasOne("My.Talli.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OrderItem_Product");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.Product", b =>
                {
                    b.HasOne("My.Talli.Domain.Entities.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Product_ProductType");

                    b.HasOne("My.Talli.Domain.Entities.ProductVendor", "ProductVendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Product_ProductVendor");

                    b.Navigation("ProductType");

                    b.Navigation("ProductVendor");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("My.Talli.Domain.Entities.OrderItem", "OrderItem")
                        .WithMany()
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Subscription_OrderItem");

                    b.HasOne("My.Talli.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Subscription_Product");

                    b.HasOne("My.Talli.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Subscription_User");

                    b.Navigation("OrderItem");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.SubscriptionStripe", b =>
                {
                    b.HasOne("My.Talli.Domain.Entities.Subscription", "Subscription")
                        .WithOne()
                        .HasForeignKey("My.Talli.Domain.Entities.SubscriptionStripe", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SubscriptionStripe_Subscription");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.UserAuthenticationApple", b =>
                {
                    b.HasOne("My.Talli.Domain.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("My.Talli.Domain.Entities.UserAuthenticationApple", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserAuthApple_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.UserAuthenticationGoogle", b =>
                {
                    b.HasOne("My.Talli.Domain.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("My.Talli.Domain.Entities.UserAuthenticationGoogle", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserAuthGoogle_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.UserAuthenticationMicrosoft", b =>
                {
                    b.HasOne("My.Talli.Domain.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("My.Talli.Domain.Entities.UserAuthenticationMicrosoft", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserAuthMicrosoft_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("My.Talli.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("My.Talli.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserRole_User");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
